name: Build Windows

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: HoLingoko.py
          mode: app
          enable-plugins: pyside6
          include-data-dir: resources=resources
          windows-console-mode: disable
          windows-icon-from-ico: resources/images/icon.png

      - name: Build Installer
        run: |
          iscc.exe windows/build_windows_installer.iss

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            windows/Output/*.exe
          include-hidden-files: true
